### PR TITLE
Update security-prefs.js

### PR DESCRIPTION
**Pull request by LeoKids**
Make it more consistent and less annoying to browse.

### CODE REVIEW

**Comment by LeoKids** [comment]
@roytam1 


Needs #1 to be successful

**Comment by roytam1** [comment]
see https://github.com/roytam1/RetroZilla/pull/1#issuecomment-2439626577

**Comment by LeoKids** [comment]
> see #1 


Just saw.

**Comment by LeoKids** [comment]
These pref names are intended inconsistency. Closing in favor of #3

**Pull request closed without merging**
