### PR TITLE
Update nsNSSComponent.cpp

### PR DESCRIPTION
**Pull request by LeoKids**
Won't work without changing this

### CODE REVIEW

**Comment by LeoKids** [comment]
@roytam1

**Comment by LeoKids** [comment]
Also needs #2 to be successful

**Comment by roytam1** [comment]
I don't think there is a need of changing pref name

**Comment by LeoKids** [comment]
> @roytam1:
I don't think there is a need of changing pref name



It's needed for consistency with others pref names,who just says SSL3.

**Comment by LeoKids** [comment]
@roytam1 Any response?

**Comment by roytam1** [comment]
> @roytam1 Any response?

see https://github.com/roytam1/RetroZilla/pull/1#issuecomment-2439626577

**Comment by LeoKids** [comment]
> see https://github.com/roytam1/RetroZilla/pull/1#issuecomment-2439626577

I already readed it already and i said it's needed for consistency with other pref names who just says ssl3. @roytam1

**Comment by LeoKids** [comment]
Besides,roytam1,you never readed this https://github.com/roytam1/RetroZilla/pull/1#issuecomment-2439657015


If you readed this,you'd understand it is needed.

**Comment by roytam1** [comment]
> i said it's needed for consistency with other pref names who just says ssl3.

it is intended inconsistency since they're for TLS 1.3 only.

**Comment by LeoKids** [comment]
> > i said it's needed for consistency with other pref names who just says ssl3.
> 
> it is intended inconsistency since they're for TLS 1.3 only.

It wasn't intended to be inconsistency just because they're TLS 1.3 only,besides do you wanna merge but without changing pref names, though?

**Comment by LeoKids** [comment]
Please keep ìt consistent though, even if it's intended to be inconsistent. @roytam1

**Pull request closed without merging**
